# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ISSpredict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userselect', models.IntegerField(verbose_name='User')),
                ('lat', models.FloatField(verbose_name='Latitude')),
                ('lon', models.FloatField(verbose_name='Longitude')),
            ],
        ),
        migrations.CreateModel(
            name='OrbitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('night', models.BooleanField()),
                ('orbitstr', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ScienceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='Latitude')),
                ('lon', models.FloatField(verbose_name='Longitude')),
                ('obsid', models.IntegerField(verbose_name='ObservationId')),
                ('date', models.DateTimeField(verbose_name='Date Observed')),
                ('trig', models.CharField(max_length=200)),
                ('inst', models.CharField(max_length=200)),
                ('lev0', models.CharField(max_length=200)),
                ('lev1', models.CharField(max_length=200)),
                ('prev', models.CharField(max_length=200)),
            ],
        ),
    ]
